{% set name = "dapclient" %}
{% set version = "1.0.6" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dapclient-{{ version }}.tar.gz
  sha256: f38b133561009aaf9a0af5414753a2619f504fac26f3669e10a2f8db4739d70c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - numpy
    - requests
    - webob

test:
  imports:
    - dapclient
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A client-only fork of pydap using the DAP protocol to access scientific data on the internet.
  home: https://pypi.org/project/dapclient/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
