{% set name = "dapclient" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dapclient-{{ version }}.tar.gz
  sha256: 323d9394d3e2dc0ffd8067373c679448b4356c2e1869aa8d1ed54298017ce753

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - requests
    - webob
    - beautifulsoup4

test:
  imports:
    - dapclient
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A client-only fork of pydap using the DAP protocol to access scientific data on the internet.
  home: https://pypi.org/project/dapclient/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
